# Generated by Django 4.1.2 on 2022-10-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heros',
            fields=[
                ('heroId', models.AutoField(primary_key=True, serialize=False)),
                ('heroName', models.CharField(max_length=100)),
            ],
        ),
    ]
